config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index] do
    resources :plays, only: [:index, :show, :create] do
      resources :turns, only: [:index, :show, :create]
    end
  end

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :plays
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :game
  has_many :turns
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/turn.rb
class Turn < ActiveRecord::Base
  belongs_to :play
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def index
    @game = Game.find(params["game_id"])
    @plays = @game.plays
  end

  def show
    @game = Game.find(params["game_id"])
    @play = @game.plays.find(params["id"])
  end

  def create
    @game = Game.find(params["game_id"])
    @play = @game.plays.create
    redirect_to game_play_path(@game, @play)
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  def index
  end

  def show
    @game = Game.find(params["game_id"])
    @play = @game.plays.find(params["play_id"])
    @turn = @play.turns.find(params["id"])
  end

  def create
    @game = Game.find(params["game_id"])
    @play = @game.plays.find(params["play_id"])
    @turn = @play.turns.create
    redirect_to game_play_turn_path(@game, @play, @turn)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bxst</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plays/index.html.erb
<h1>Game</h1>
<h3>ID: <%= @game.id %></h3>

<h2>Play Sessions</h2>
<%= button_to "Play session", game_plays_path(@game.id) %>

app/views/plays/show.html.erb
<h1>Play session</h1>
<h3>ID: <%= @play.id %></h3>
<p>Status: In progress</p>

<h2>Turns</h2>
<%= button_to "Start play session", game_play_turns_path(@game, @play) %>

app/views/turns/show.html.erb
<h1>Turn</h1>
<h3>ID: <%= @turn.id %></h3>
<p>Status: In progress</p>